### ISSUE TITLE
[project] Vitest coverage only shows one (random) package in report

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#106]
How can we get it to collect coverage for each of the packages under test?

**Comment by Alchez** [comment]
@agritheory So the vitest coverage report on the PR is built by the https://github.com/davelosert/vitest-coverage-report-action tool. When I had set it up initially, it didn't have support for monorepos. However, there seems to be [documentation](https://github.com/davelosert/vitest-coverage-report-action#workspaces) on getting it to work with [Vitest Workspaces](https://vitest.dev/guide/workspace.html).

I could try it out sometime and see if it works. Otherwise I can remove the comment feature and we could individually check each project's coverage reports.

**Comment by agritheory** [comment]
@Alchez Yes, we're looking for project level coverage reports. The documented approach looks promising.
