### ISSUE TITLE
[ATable] Freeze columns

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#142]

**Comment by Alchez** [comment]
@agritheory It seems like this is going to be a CSS solution most likely, so maybe we also bring Curt into this ticket?

On the setup side though:
- How should a user decide which column(s) to freeze?
  - Should it be a per-column config (which will allow any arbitrary column to be frozen)?
  - And/or should it be part of the table config (which may allow defining "preset" columns to be frozen, like "first", "last", "header", etc)?
- Should we allow multiple columns to be frozen (we might have to implicitly freeze the index column anyway)?
  - How should the view work if the columns are not consecutively placed?
- Should we allow sticky columns in all views (list, tree, list-expansion)?

**Comment by agritheory** [comment]
It would be good to understand what the options are via CSS. The minimal requirement is to be able to freeze columns from the leftmost to the Nth position. Having a column in the middle be frozen _could_ be configurable but I don't really know in what user story that makes sense. 

It should be defined in the table config, I consider this to be something that's defined by the schema. AG Grid uses "pinned" as the terminology, which I think is clearer than 'freeze', which could imply that those field are also not editable, when they could be. [docs](https://www.ag-grid.com/vue-data-grid/column-pinning/)

I think we should try to implement this in the tree and expansion row setups as well, though I don't think it will always look great. Let's experiment.

@crabinak Would love to hear some of your thoughts as well.

**Comment by crabinak** [comment]
@agritheory @Alchez Is Ag-Grid being used for this or is that linked just as an example?

There is a three-column layout here: _Left pinned, Scroll content, and Right pinned_. Based on the pinning options, left or right pinned is hidden if no pinning is specified for that side (by default everything is in the overflow:scroll section). From what I can tell, there is no CSS classes being adjusted but rather the columns are being rearranged and placed into their appropriate section based on the pinning options via JS. 

The table is rebuilt by placing pinned columns into the left (or right if chosen) section, which will remain pinned, and the remaining columns are placed in the scrollable section. The cells use fixed heights and absolute positioning, they are positioned at (index*cell_height) when added. As this is all inline styling being adjusted, it would appear to be added by JS instead of CSS since this needs to dynamically updated based on pinning options. This makes sense because you'd have a variable number of cells being dynamically placed.

There is no option to middle pin and for good reason (that would be a nightmare to use). Instead, if you want a middle column pinned, it just gets rebuilt and moved to the Left pin section (the columns reorder so you don't get pinned columns stuck in the middle; all pinned columns are grouped together). This probably uses the same logic the drag-and-drop column feature uses to reorder.

**Comment by agritheory** [comment]
@crabinak AG Grid will not be used. Their product is more complicated than we need and its licensing is a mess. They already have this feature and it's something we want to also develop.

[This stackoverflow thread](https://stackoverflow.com/questions/1312236/how-do-i-create-an-html-table-with-a-fixed-frozen-left-column-and-a-scrollable-b) has some different types of solutions, the sticky one looks most promising to me.

**Comment by crabinak** [comment]
@agritheory @Alchez I have an offshoot of the feat-pinned-columns branch [feat-pinned-columns-ordering](https://github.com/agritheory/stonecrop/tree/feat-pinned-columns-ordering) where I've been working on getting this functioning because I had a feeling it might get a bit messy. 

I have this set up where sticky columns will move to the left of non-sticky ones (as an example, the HTTP method column is set to be sticky and appears as the leftmost column). _The header styling is messed up here and does not utilize the sticky feature at the moment and a few other styles also need to be fixed._ 

Where I am stuck is that each pinned cell will need to know the cumulative widths of all pinned cells that preceded it within the row and then set its inline style left property to that value (this is because the width of columns and the number of sticky columns is not constant). Otherwise, all pinned columns will just start stacking on top of each other. I'm not quite sure how to get that value at the moment.

**Comment by Alchez** [comment]
@crabinak I'm not sure if this would work, but maybe we need a combination of:
- Use the `TableDataStore` class to keep track of current pinned columns
- Add a computed property in `ACell.vue` that dynamically calculates the `left` value for each pinned column
- Pass the computed property's value to the style using [`v-bind`](https://vuejs.org/api/sfc-css-features.html#v-bind-in-css)

What do you think?
