### ISSUE TITLE
FSM and Hook Implementation 

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#34]
Every Doctype shall have a finite state machine. These describe the flow of states /statuses of data in its user-facing context. Nested machines (an Order having an externally derived "Paid" or Delivered" state) are fine, as are trivial machines (an Access Log Doctype with only "Created" and "Saved" states for example). These FSM will be enforced on both the server and in the UI so they need to be mutually compatible/ client-agnostic. The FSM will fire hooks - events stored in a map as part of the metadata - to create mutations to the document and/or side effects. At this time hooks can be plain functions but it is likely that we will expand them to include more metadata in the future (client/server-only flags, permissions, idempotency implementation, etc).

This POC contains several scopes of development: 
- [x] FSM integration
- [x] Hooks implementation

The following are moved to #35 and out of scope of this Issue:
- A [`Workflow` UI component](https://github.com/agritheory/stonecrop/issues/35) allows the user to create a document and interact with its state (part of Stonecrop)
- A subset of the `Workflow` component will be a button / button group design effort (port of AForm)

**Comment by Alchez** [comment]
Okay, so I created a simple machine that should cover a basic flow of a doctype/record.

https://stately.ai/viz/52c75195-1762-4a9b-acae-e251f6765d42

Now my questions are:
- **[FSM]** Should the server be expected to send over a [`MachineConfig`](https://xstate.js.org/docs/guides/typescript.html#config-objects)-like object when the registry is being populated? And then Stonecrop converts that into a [`StateMachine`](https://xstate.js.org/docs/packages/xstate-fsm/#createmachine-config-options) for use? The config can be stored in the registry and remain immutable.
  - Should the registry be able to handle primitives as well for the events? A configuration that does not convert into a machine, and hooks are handled as the implementation sees fit?
  - If we enforce the MachineConfig route, that also means that Stonecrop has an opinion that the implementation should use XState.
- **[FSM]** I'm not sure who should be responsible for the machine instance? Should it be part of the registry (and per doctype/records), or should the state management for that be deferred to the implementation using the registry?
- **[Hooks]** Since events and hooks are connected to each other via machine transitions, should they be combined into a single configuration?
- **[Typing]** Currently, Stonecrop assumes that the `schema` object that the server sends is a `list` of fields, which is fine for our story.
  - I'm leaning towards making it an `any` or `unknown` type (and allow the client to setup models when adding to the registry) to accommodate for schemas provided by a backend like Frappe's (with `fields` being just a key in the schema). That should make stonecrop agnostic to the different kinds of schemas. What do you think?

I don't know how much these questions will directly impact the first iteration of the FSM/hooks story, since we can wire something up as a PoC, but this will probably help setup future iterations.

**Comment by agritheory** [comment]
@Alchez @johnhkelley1 Let' use this as the agenda for the call tomorrow,, this will serve as a good structure

**Comment by agritheory** [comment]
> [FSM] Should the server be expected to send over a [MachineConfig](https://xstate.js.org/docs/guides/typescript.html#config-objects)-like object when the registry is being populated?

Yes, the registry should expect a complete Doctype. All Doctypes will have an FSM regardless of how trivial they are.

> Should the registry be able to handle primitives as well for the events? A configuration that does not convert into a machine, and hooks are handled as the implementation sees fit?

Yes, but not required for the first pass, unless its a blocking issue.

> If we enforce the MachineConfig route, that also means that Stonecrop has an opinion that the implementation should use XState.

This is a reasonable opinion and I'm OK with it. Theoretically the HTTP client could mutate the FSM into a XState compatible form if it were stored in some other way, but it would be preferable that this be handled on the server (out of scope). 

> [FSM] I'm not sure who should be responsible for the machine instance? Should it be part of the registry (and per doctype/records), or should the state management for that be deferred to the implementation using the registry?

The registry can track the machine instance. The record must have a key/ field to store its state. I think this will shake out in the implementation and could introduce a little bit of creep. Circle back to discuss if the path get murky.
